version: "3.3"
services:
  tcptunnel:
    container_name: tcptunnel
    build:
      context: .
      args:
        http_proxy: http://localhost:8888
        https_proxy: http://localhost:8888
    network_mode: host
    environment:
      env_file: .env
    restart: unless-stopped
